// /// Enum for countries with validation regex patterns.
// enum CountryEnum {
//   afghanistan(
//     name: "Afghanistan",
//     code: "AF",
//     dialCode: "+93",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   alandIslands(
//     name: "Åland Islands",
//     code: "AX",
//     dialCode: "+358",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   albania(
//     name: "Albania",
//     code: "AL",
//     dialCode: "+355",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   algeria(
//     name: "Algeria",
//     code: "DZ",
//     dialCode: "+213",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   americanSamoa(
//     name: "American Samoa",
//     code: "AS",
//     dialCode: "+1-684",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   andorra(
//     name: "Andorra",
//     code: "AD",
//     dialCode: "+376",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   angola(
//     name: "Angola",
//     code: "AO",
//     dialCode: "+244",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   anguilla(
//     name: "Anguilla",
//     code: "AI",
//     dialCode: "+1-264",
//     postalCodePattern: r'^AI-2640$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   antarctica(
//     name: "Antarctica",
//     code: "AQ",
//     dialCode: "none",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   antiguaAndBarbuda(
//     name: "Antigua and Barbuda",
//     code: "AG",
//     dialCode: "+1-268",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   argentina(
//     name: "Argentina",
//     code: "AR",
//     dialCode: "+54",
//     postalCodePattern: r'^[A-Z]\d{4}[A-Z]{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   armenia(
//     name: "Armenia",
//     code: "AM",
//     dialCode: "+374",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   aruba(
//     name: "Aruba",
//     code: "AW",
//     dialCode: "+297",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   australia(
//     name: "Australia",
//     code: "AU",
//     dialCode: "+61",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   austria(
//     name: "Austria",
//     code: "AT",
//     dialCode: "+43",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   azerbaijan(
//     name: "Azerbaijan",
//     code: "AZ",
//     dialCode: "+994",
//     postalCodePattern: r'^AZ\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bahamas(
//     name: "Bahamas",
//     code: "BS",
//     dialCode: "+1-242",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bahrain(
//     name: "Bahrain",
//     code: "BH",
//     dialCode: "+973",
//     postalCodePattern: r'^\d{3,4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bangladesh(
//     name: "Bangladesh",
//     code: "BD",
//     dialCode: "+880",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   barbados(
//     name: "Barbados",
//     code: "BB",
//     dialCode: "+1-246",
//     postalCodePattern: r'^BB\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   belarus(
//     name: "Belarus",
//     code: "BY",
//     dialCode: "+375",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   belgium(
//     name: "Belgium",
//     code: "BE",
//     dialCode: "+32",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   belize(
//     name: "Belize",
//     code: "BZ",
//     dialCode: "+501",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   benin(
//     name: "Benin",
//     code: "BJ",
//     dialCode: "+229",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bermuda(
//     name: "Bermuda",
//     code: "BM",
//     dialCode: "+1-441",
//     postalCodePattern: r'^[A-Z]{2}\s?[A-Z0-9]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bhutan(
//     name: "Bhutan",
//     code: "BT",
//     dialCode: "+975",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bolivia(
//     name: "Bolivia",
//     code: "BO",
//     dialCode: "+591",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bosniaAndHerzegovina(
//     name: "Bosnia and Herzegovina",
//     code: "BA",
//     dialCode: "+387",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   botswana(
//     name: "Botswana",
//     code: "BW",
//     dialCode: "+267",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bouvetIsland(
//     name: "Bouvet Island",
//     code: "BV",
//     dialCode: "+47",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   brazil(
//     name: "Brazil",
//     code: "BR",
//     dialCode: "+55",
//     postalCodePattern: r'^\d{5}-\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   britishIndianOceanTerritory(
//     name: "British Indian Ocean Territory",
//     code: "IO",
//     dialCode: "+246",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bruneiDarussalam(
//     name: "Brunei Darussalam",
//     code: "BN",
//     dialCode: "+673",
//     postalCodePattern: r'^[A-Z]{2}\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   bulgaria(
//     name: "Bulgaria",
//     code: "BG",
//     dialCode: "+359",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   burkinaFaso(
//     name: "Burkina Faso",
//     code: "BF",
//     dialCode: "+226",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   burundi(
//     name: "Burundi",
//     code: "BI",
//     dialCode: "+257",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cambodia(
//     name: "Cambodia",
//     code: "KH",
//     dialCode: "+855",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cameroon(
//     name: "Cameroon",
//     code: "CM",
//     dialCode: "+237",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   canada(
//     name: "Canada",
//     code: "CA",
//     dialCode: "+1",
//     postalCodePattern: r'^[A-Z]\d[A-Z]\s?\d[A-Z]\d$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   capeVerde(
//     name: "Cape Verde",
//     code: "CV",
//     dialCode: "+238",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   caymanIslands(
//     name: "Cayman Islands",
//     code: "KY",
//     dialCode: "+1-345",
//     postalCodePattern: r'^[A-Z]{2}\d{1}-\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   centralAfricanRepublic(
//     name: "Central African Republic",
//     code: "CF",
//     dialCode: "+236",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   chad(
//     name: "Chad",
//     code: "TD",
//     dialCode: "+235",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   chile(
//     name: "Chile",
//     code: "CL",
//     dialCode: "+56",
//     postalCodePattern: r'^\d{7}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   china(
//     name: "China",
//     code: "CN",
//     dialCode: "+86",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   christmasIsland(
//     name: "Christmas Island",
//     code: "CX",
//     dialCode: "+61",
//     postalCodePattern: r'^6798$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cocosKeelingIslands(
//     name: "Cocos (Keeling) Islands",
//     code: "CC",
//     dialCode: "+61",
//     postalCodePattern: r'^6799$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   colombia(
//     name: "Colombia",
//     code: "CO",
//     dialCode: "+57",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   comoros(
//     name: "Comoros",
//     code: "KM",
//     dialCode: "+269",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   congo(
//     name: "Congo",
//     code: "CG",
//     dialCode: "+242",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   congoTheDemocraticRepublicOfThe(
//     name: "Congo, The Democratic Republic of the",
//     code: "CD",
//     dialCode: "+243",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cookIslands(
//     name: "Cook Islands",
//     code: "CK",
//     dialCode: "+682",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   costaRica(
//     name: "Costa Rica",
//     code: "CR",
//     dialCode: "+506",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   coteDIvoire(
//     name: "Cote D'Ivoire",
//     code: "CI",
//     dialCode: "+225",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   croatia(
//     name: "Croatia",
//     code: "HR",
//     dialCode: "+385",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cuba(
//     name: "Cuba",
//     code: "CU",
//     dialCode: "+53",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   cyprus(
//     name: "Cyprus",
//     code: "CY",
//     dialCode: "+357",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   czechRepublic(
//     name: "Czech Republic",
//     code: "CZ",
//     dialCode: "+420",
//     postalCodePattern: r'^\d{3}\s?\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   denmark(
//     name: "Denmark",
//     code: "DK",
//     dialCode: "+45",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   djibouti(
//     name: "Djibouti",
//     code: "DJ",
//     dialCode: "+253",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   dominica(
//     name: "Dominica",
//     code: "DM",
//     dialCode: "+1-767",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   dominicanRepublic(
//     name: "Dominican Republic",
//     code: "DO",
//     dialCode: "+1-809",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ecuador(
//     name: "Ecuador",
//     code: "EC",
//     dialCode: "+593",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   egypt(
//     name: "Egypt",
//     code: "EG",
//     dialCode: "+20",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   elSalvador(
//     name: "El Salvador",
//     code: "SV",
//     dialCode: "+503",
//     postalCodePattern: r'^[A-Z]{2}\s?\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   equatorialGuinea(
//     name: "Equatorial Guinea",
//     code: "GQ",
//     dialCode: "+240",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   eritrea(
//     name: "Eritrea",
//     code: "ER",
//     dialCode: "+291",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   estonia(
//     name: "Estonia",
//     code: "EE",
//     dialCode: "+372",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ethiopia(
//     name: "Ethiopia",
//     code: "ET",
//     dialCode: "+251",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   falklandIslandsMalvinas(
//     name: "Falkland Islands (Malvinas)",
//     code: "FK",
//     dialCode: "+500",
//     postalCodePattern: r'^FIQQ\s?1ZZ$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   faroeIslands(
//     name: "Faroe Islands",
//     code: "FO",
//     dialCode: "+298",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   fiji(
//     name: "Fiji",
//     code: "FJ",
//     dialCode: "+679",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   finland(
//     name: "Finland",
//     code: "FI",
//     dialCode: "+358",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   france(
//     name: "France",
//     code: "FR",
//     dialCode: "+33",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   frenchGuiana(
//     name: "French Guiana",
//     code: "GF",
//     dialCode: "+594",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   frenchPolynesia(
//     name: "French Polynesia",
//     code: "PF",
//     dialCode: "+689",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   frenchSouthernTerritories(
//     name: "French Southern Territories",
//     code: "TF",
//     dialCode: "+262",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   gabon(
//     name: "Gabon",
//     code: "GA",
//     dialCode: "+241",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   gambia(
//     name: "Gambia",
//     code: "GM",
//     dialCode: "+220",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   georgia(
//     name: "Georgia",
//     code: "GE",
//     dialCode: "+995",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   germany(
//     name: "Germany",
//     code: "DE",
//     dialCode: "+49",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ghana(
//     name: "Ghana",
//     code: "GH",
//     dialCode: "+233",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   gibraltar(
//     name: "Gibraltar",
//     code: "GI",
//     dialCode: "+350",
//     postalCodePattern: r'^GX11\s?1AA$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   greece(
//     name: "Greece",
//     code: "GR",
//     dialCode: "+30",
//     postalCodePattern: r'^\d{3}\s?\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   greenland(
//     name: "Greenland",
//     code: "GL",
//     dialCode: "+299",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   grenada(
//     name: "Grenada",
//     code: "GD",
//     dialCode: "+1-473",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guadeloupe(
//     name: "Guadeloupe",
//     code: "GP",
//     dialCode: "+590",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guam(
//     name: "Guam",
//     code: "GU",
//     dialCode: "+1-671",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guatemala(
//     name: "Guatemala",
//     code: "GT",
//     dialCode: "+502",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guernsey(
//     name: "Guernsey",
//     code: "GG",
//     dialCode: "+44-1481",
//     postalCodePattern: r'^G(G|Y)\d{1,2}\s?\d[A-Z]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guinea(
//     name: "Guinea",
//     code: "GN",
//     dialCode: "+224",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guineaBissau(
//     name: "Guinea-Bissau",
//     code: "GW",
//     dialCode: "+245",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   guyana(
//     name: "Guyana",
//     code: "GY",
//     dialCode: "+592",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   haiti(
//     name: "Haiti",
//     code: "HT",
//     dialCode: "+509",
//     postalCodePattern: r'^[A-Z]{2}\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   heardIslandAndMcdonaldIslands(
//     name: "Heard Island and Mcdonald Islands",
//     code: "HM",
//     dialCode: "none",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   holySeeVaticanCityState(
//     name: "Holy See (Vatican City State)",
//     code: "VA",
//     dialCode: "+379",
//     postalCodePattern: r'^00120$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   honduras(
//     name: "Honduras",
//     code: "HN",
//     dialCode: "+504",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   hongKong(
//     name: "Hong Kong",
//     code: "HK",
//     dialCode: "+852",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   hungary(
//     name: "Hungary",
//     code: "HU",
//     dialCode: "+36",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   iceland(
//     name: "Iceland",
//     code: "IS",
//     dialCode: "+354",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   india(
//     name: "India",
//     code: "IN",
//     dialCode: "+91",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   indonesia(
//     name: "Indonesia",
//     code: "ID",
//     dialCode: "+62",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   iranIslamicRepublicOf(
//     name: "Iran, Islamic Republic Of",
//     code: "IR",
//     dialCode: "+98",
//     postalCodePattern: r'^\d{10}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   iraq(
//     name: "Iraq",
//     code: "IQ",
//     dialCode: "+964",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ireland(
//     name: "Ireland",
//     code: "IE",
//     dialCode: "+353",
//     postalCodePattern: r'^[A-Z]{1}\d{2}\s?[A-Z0-9]{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   isleOfMan(
//     name: "Isle of Man",
//     code: "IM",
//     dialCode: "+44-1624",
//     postalCodePattern: r'^[A-Z]{2}\d{1,2}\s?\d[A-Z]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   israel(
//     name: "Israel",
//     code: "IL",
//     dialCode: "+972",
//     postalCodePattern: r'^\d{5}(\d{2})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   italy(
//     name: "Italy",
//     code: "IT",
//     dialCode: "+39",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   jamaica(
//     name: "Jamaica",
//     code: "JM",
//     dialCode: "+1-876",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   japan(
//     name: "Japan",
//     code: "JP",
//     dialCode: "+81",
//     postalCodePattern: r'^\d{3}-\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   jersey(
//     name: "Jersey",
//     code: "JE",
//     dialCode: "+44-1534",
//     postalCodePattern: r'^[A-Z]{2}\d{1,2}\s?\d[A-Z]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   jordan(
//     name: "Jordan",
//     code: "JO",
//     dialCode: "+962",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   kazakhstan(
//     name: "Kazakhstan",
//     code: "KZ",
//     dialCode: "+7",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   kenya(
//     name: "Kenya",
//     code: "KE",
//     dialCode: "+254",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   kiribati(
//     name: "Kiribati",
//     code: "KI",
//     dialCode: "+686",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   koreaDemocraticPeoplesRepublicOf(
//     name: "Korea, Democratic People'S Republic of",
//     code: "KP",
//     dialCode: "+850",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   koreaRepublicOf(
//     name: "Korea, Republic of",
//     code: "KR",
//     dialCode: "+82",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   kuwait(
//     name: "Kuwait",
//     code: "KW",
//     dialCode: "+965",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   kyrgyzstan(
//     name: "Kyrgyzstan",
//     code: "KG",
//     dialCode: "+996",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   laoPeoplesDemocraticRepublic(
//     name: "Lao People'S Democratic Republic",
//     code: "LA",
//     dialCode: "+856",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   latvia(
//     name: "Latvia",
//     code: "LV",
//     dialCode: "+371",
//     postalCodePattern: r'^LV-\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   lebanon(
//     name: "Lebanon",
//     code: "LB",
//     dialCode: "+961",
//     postalCodePattern: r'^\d{4}\s?\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   lesotho(
//     name: "Lesotho",
//     code: "LS",
//     dialCode: "+266",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   liberia(
//     name: "Liberia",
//     code: "LR",
//     dialCode: "+231",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   libyanArabJamahiriya(
//     name: "Libyan Arab Jamahiriya",
//     code: "LY",
//     dialCode: "+218",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   liechtenstein(
//     name: "Liechtenstein",
//     code: "LI",
//     dialCode: "+423",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   lithuania(
//     name: "Lithuania",
//     code: "LT",
//     dialCode: "+370",
//     postalCodePattern: r'^LT-\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   luxembourg(
//     name: "Luxembourg",
//     code: "LU",
//     dialCode: "+352",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   macao(
//     name: "Macao",
//     code: "MO",
//     dialCode: "+853",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   macedoniaTheFormerYugoslavRepublicOf(
//     name: "Macedonia, The Former Yugoslav Republic of",
//     code: "MK",
//     dialCode: "+389",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   madagascar(
//     name: "Madagascar",
//     code: "MG",
//     dialCode: "+261",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   malawi(
//     name: "Malawi",
//     code: "MW",
//     dialCode: "+265",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   malaysia(
//     name: "Malaysia",
//     code: "MY",
//     dialCode: "+60",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   maldives(
//     name: "Maldives",
//     code: "MV",
//     dialCode: "+960",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mali(
//     name: "Mali",
//     code: "ML",
//     dialCode: "+223",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   malta(
//     name: "Malta",
//     code: "MT",
//     dialCode: "+356",
//     postalCodePattern: r'^[A-Z]{3}\s?\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   marshallIslands(
//     name: "Marshall Islands",
//     code: "MH",
//     dialCode: "+692",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   martinique(
//     name: "Martinique",
//     code: "MQ",
//     dialCode: "+596",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mauritania(
//     name: "Mauritania",
//     code: "MR",
//     dialCode: "+222",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mauritius(
//     name: "Mauritius",
//     code: "MU",
//     dialCode: "+230",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mayotte(
//     name: "Mayotte",
//     code: "YT",
//     dialCode: "+262",
//     postalCodePattern: r'^976\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mexico(
//     name: "Mexico",
//     code: "MX",
//     dialCode: "+52",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   micronesiaFederatedStatesOf(
//     name: "Micronesia, Federated States of",
//     code: "FM",
//     dialCode: "+691",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   moldovaRepublicOf(
//     name: "Moldova, Republic of",
//     code: "MD",
//     dialCode: "+373",
//     postalCodePattern: r'^MD-\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   monaco(
//     name: "Monaco",
//     code: "MC",
//     dialCode: "+377",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mongolia(
//     name: "Mongolia",
//     code: "MN",
//     dialCode: "+976",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   montserrat(
//     name: "Montserrat",
//     code: "MS",
//     dialCode: "+1-664",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   morocco(
//     name: "Morocco",
//     code: "MA",
//     dialCode: "+212",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   mozambique(
//     name: "Mozambique",
//     code: "MZ",
//     dialCode: "+258",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   myanmar(
//     name: "Myanmar",
//     code: "MM",
//     dialCode: "+95",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   namibia(
//     name: "Namibia",
//     code: "NA",
//     dialCode: "+264",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   nauru(
//     name: "Nauru",
//     code: "NR",
//     dialCode: "+674",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   nepal(
//     name: "Nepal",
//     code: "NP",
//     dialCode: "+977",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   netherlands(
//     name: "Netherlands",
//     code: "NL",
//     dialCode: "+31",
//     postalCodePattern: r'^\d{4}\s?[A-Z]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   netherlandsAntilles(
//     name: "Netherlands Antilles",
//     code: "AN",
//     dialCode: "none",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   newCaledonia(
//     name: "New Caledonia",
//     code: "NC",
//     dialCode: "+687",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   newZealand(
//     name: "New Zealand",
//     code: "NZ",
//     dialCode: "+64",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   nicaragua(
//     name: "Nicaragua",
//     code: "NI",
//     dialCode: "+505",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   niger(
//     name: "Niger",
//     code: "NE",
//     dialCode: "+227",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   nigeria(
//     name: "Nigeria",
//     code: "NG",
//     dialCode: "+234",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   niue(
//     name: "Niue",
//     code: "NU",
//     dialCode: "+683",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   norfolkIsland(
//     name: "Norfolk Island",
//     code: "NF",
//     dialCode: "+672",
//     postalCodePattern: r'^2899$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   northernMarianaIslands(
//     name: "Northern Mariana Islands",
//     code: "MP",
//     dialCode: "+1-670",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   norway(
//     name: "Norway",
//     code: "NO",
//     dialCode: "+47",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   oman(
//     name: "Oman",
//     code: "OM",
//     dialCode: "+968",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   pakistan(
//     name: "Pakistan",
//     code: "PK",
//     dialCode: "+92",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   palau(
//     name: "Palau",
//     code: "PW",
//     dialCode: "+680",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   palestinianTerritoryOccupied(
//     name: "Palestinian Territory, Occupied",
//     code: "PS",
//     dialCode: "+970",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   panama(
//     name: "Panama",
//     code: "PA",
//     dialCode: "+507",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   papuaNewGuinea(
//     name: "Papua New Guinea",
//     code: "PG",
//     dialCode: "+675",
//     postalCodePattern: r'^\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   paraguay(
//     name: "Paraguay",
//     code: "PY",
//     dialCode: "+595",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   peru(
//     name: "Peru",
//     code: "PE",
//     dialCode: "+51",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   philippines(
//     name: "Philippines",
//     code: "PH",
//     dialCode: "+63",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   pitcairn(
//     name: "Pitcairn",
//     code: "PN",
//     dialCode: "+64",
//     postalCodePattern: r'^PCRN\s?1ZZ$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   poland(
//     name: "Poland",
//     code: "PL",
//     dialCode: "+48",
//     postalCodePattern: r'^\d{2}-\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   portugal(
//     name: "Portugal",
//     code: "PT",
//     dialCode: "+351",
//     postalCodePattern: r'^\d{4}-\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   puertoRico(
//     name: "Puerto Rico",
//     code: "PR",
//     dialCode: "+1-787",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   qatar(
//     name: "Qatar",
//     code: "QA",
//     dialCode: "+974",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   reunion(
//     name: "Reunion",
//     code: "RE",
//     dialCode: "+262",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   romania(
//     name: "Romania",
//     code: "RO",
//     dialCode: "+40",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   russianFederation(
//     name: "Russian Federation",
//     code: "RU",
//     dialCode: "+7",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   rwanda(
//     name: "RWANDA",
//     code: "RW",
//     dialCode: "+250",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saintHelena(
//     name: "Saint Helena",
//     code: "SH",
//     dialCode: "+290",
//     postalCodePattern: r'^STHL\s?1ZZ$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saintKittsAndNevis(
//     name: "Saint Kitts and Nevis",
//     code: "KN",
//     dialCode: "+1-869",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saintLucia(
//     name: "Saint Lucia",
//     code: "LC",
//     dialCode: "+1-758",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saintPierreAndMiquelon(
//     name: "Saint Pierre and Miquelon",
//     code: "PM",
//     dialCode: "+508",
//     postalCodePattern: r'^97500$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saintVincentAndTheGrenadines(
//     name: "Saint Vincent and the Grenadines",
//     code: "VC",
//     dialCode: "+1-784",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   samoa(
//     name: "Samoa",
//     code: "WS",
//     dialCode: "+685",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   sanMarino(
//     name: "San Marino",
//     code: "SM",
//     dialCode: "+378",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saoTomeAndPrincipe(
//     name: "Sao Tome and Principe",
//     code: "ST",
//     dialCode: "+239",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   saudiArabia(
//     name: "Saudi Arabia",
//     code: "SA",
//     dialCode: "+966",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   senegal(
//     name: "Senegal",
//     code: "SN",
//     dialCode: "+221",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   serbiaAndMontenegro(
//     name: "Serbia and Montenegro",
//     code: "CS",
//     dialCode: "none",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   seychelles(
//     name: "Seychelles",
//     code: "SC",
//     dialCode: "+248",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   sierraLeone(
//     name: "Sierra Leone",
//     code: "SL",
//     dialCode: "+232",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   singapore(
//     name: "Singapore",
//     code: "SG",
//     dialCode: "+65",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   slovakia(
//     name: "Slovakia",
//     code: "SK",
//     dialCode: "+421",
//     postalCodePattern: r'^\d{3}\s?\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   slovenia(
//     name: "Slovenia",
//     code: "SI",
//     dialCode: "+386",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   solomonIslands(
//     name: "Solomon Islands",
//     code: "SB",
//     dialCode: "+677",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   somalia(
//     name: "Somalia",
//     code: "SO",
//     dialCode: "+252",
//     postalCodePattern: r'^[A-Z]{2}\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   southAfrica(
//     name: "South Africa",
//     code: "ZA",
//     dialCode: "+27",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   southGeorgiaAndTheSouthSandwichIslands(
//     name: "South Georgia and the South Sandwich Islands",
//     code: "GS",
//     dialCode: "+500",
//     postalCodePattern: r'^SIQQ\s?1ZZ$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   spain(
//     name: "Spain",
//     code: "ES",
//     dialCode: "+34",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   sriLanka(
//     name: "Sri Lanka",
//     code: "LK",
//     dialCode: "+94",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   sudan(
//     name: "Sudan",
//     code: "SD",
//     dialCode: "+249",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   suriname(
//     name: "Suriname",
//     code: "SR",
//     dialCode: "+597",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   svalbardAndJanMayen(
//     name: "Svalbard and Jan Mayen",
//     code: "SJ",
//     dialCode: "+47",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   swaziland(
//     name: "Swaziland",
//     code: "SZ",
//     dialCode: "+268",
//     postalCodePattern: r'^[A-Z]\d{3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   sweden(
//     name: "Sweden",
//     code: "SE",
//     dialCode: "+46",
//     postalCodePattern: r'^\d{3}\s?\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   switzerland(
//     name: "Switzerland",
//     code: "CH",
//     dialCode: "+41",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   syrianArabRepublic(
//     name: "Syrian Arab Republic",
//     code: "SY",
//     dialCode: "+963",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   taiwanProvinceOfChina(
//     name: "Taiwan, Province of China",
//     code: "TW",
//     dialCode: "+886",
//     postalCodePattern: r'^\d{3}(\d{2})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tajikistan(
//     name: "Tajikistan",
//     code: "TJ",
//     dialCode: "+992",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tanzaniaUnitedRepublicOf(
//     name: "Tanzania, United Republic of",
//     code: "TZ",
//     dialCode: "+255",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   thailand(
//     name: "Thailand",
//     code: "TH",
//     dialCode: "+66",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   timorLeste(
//     name: "Timor-Leste",
//     code: "TL",
//     dialCode: "+670",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   togo(
//     name: "Togo",
//     code: "TG",
//     dialCode: "+228",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tokelau(
//     name: "Tokelau",
//     code: "TK",
//     dialCode: "+690",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tonga(
//     name: "Tonga",
//     code: "TO",
//     dialCode: "+676",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   trinidadAndTobago(
//     name: "Trinidad and Tobago",
//     code: "TT",
//     dialCode: "+1-868",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tunisia(
//     name: "Tunisia",
//     code: "TN",
//     dialCode: "+216",
//     postalCodePattern: r'^\d{4}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   turkey(
//     name: "Turkey",
//     code: "TR",
//     dialCode: "+90",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   turkmenistan(
//     name: "Turkmenistan",
//     code: "TM",
//     dialCode: "+993",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   turksAndCaicosIslands(
//     name: "Turks and Caicos Islands",
//     code: "TC",
//     dialCode: "+1-649",
//     postalCodePattern: r'^TKCA\s?1ZZ$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   tuvalu(
//     name: "Tuvalu",
//     code: "TV",
//     dialCode: "+688",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   uganda(
//     name: "Uganda",
//     code: "UG",
//     dialCode: "+256",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ukraine(
//     name: "Ukraine",
//     code: "UA",
//     dialCode: "+380",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   unitedArabEmirates(
//     name: "United Arab Emirates",
//     code: "AE",
//     dialCode: "+971",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   unitedKingdom(
//     name: "United Kingdom",
//     code: "GB",
//     dialCode: "+44",
//     postalCodePattern: r'^[A-Z]{1,2}[0-9][A-Z0-9]?\s?[0-9][A-Z]{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   unitedStates(
//     name: "United States",
//     code: "US",
//     dialCode: "+1",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   unitedStatesMinorOutlyingIslands(
//     name: "United States Minor Outlying Islands",
//     code: "UM",
//     dialCode: "+268",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   uruguay(
//     name: "Uruguay",
//     code: "UY",
//     dialCode: "+598",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   uzbekistan(
//     name: "Uzbekistan",
//     code: "UZ",
//     dialCode: "+998",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   vanuatu(
//     name: "Vanuatu",
//     code: "VU",
//     dialCode: "+678",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   venezuela(
//     name: "Venezuela",
//     code: "VE",
//     dialCode: "+58",
//     postalCodePattern: r'^\d{4}[A-Z]{2,3}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   vietNam(
//     name: "Viet Nam",
//     code: "VN",
//     dialCode: "+84",
//     postalCodePattern: r'^\d{6}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   virginIslandsBritish(
//     name: "Virgin Islands, British",
//     code: "VG",
//     dialCode: "+1-284",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   virginIslandsUS(
//     name: "Virgin Islands, U.S.",
//     code: "VI",
//     dialCode: "+1-340",
//     postalCodePattern: r'^\d{5}(-\d{4})?$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   wallisAndFutuna(
//     name: "Wallis and Futuna",
//     code: "WF",
//     dialCode: "+681",
//     postalCodePattern: r'^986\d{2}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   westernSahara(
//     name: "Western Sahara",
//     code: "EH",
//     dialCode: "none",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   yemen(
//     name: "Yemen",
//     code: "YE",
//     dialCode: "+967",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   zambia(
//     name: "Zambia",
//     code: "ZM",
//     dialCode: "+260",
//     postalCodePattern: r'^\d{5}$',
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   zimbabwe(
//     name: "Zimbabwe",
//     code: "ZW",
//     dialCode: "+263",
//     postalCodePattern: "none",
//     passportPattern: "none",
//     nationalIdPattern: "none",
//   ),
//   ;

//   final String name;
//   final String code;
//   final String dialCode;
//   final String postalCodePattern;
//   final String passportPattern;
//   final String nationalIdPattern;

//   const CountryEnum({
//     required this.name,
//     required this.code,
//     required this.dialCode,
//     required this.postalCodePattern,
//     required this.passportPattern,
//     required this.nationalIdPattern,
//   });

//   bool validatePostalCode(String v) =>
//       postalCodePattern.isNotEmpty &&
//       postalCodePattern != "none" &&
//       RegExp(postalCodePattern).hasMatch(v);

//   bool validatePassport(String v) =>
//       passportPattern.isNotEmpty &&
//       passportPattern != "none" &&
//       RegExp(passportPattern).hasMatch(v);

//   bool validateNationalId(String v) =>
//       nationalIdPattern.isNotEmpty &&
//       nationalIdPattern != "none" &&
//       RegExp(nationalIdPattern).hasMatch(v);
// }
